
spring:
  datasource:
    url: jdbc:h2:mem:notification_db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

    hibernate:
      ddl-auto: create-drop
  mail:
    host: smtp.gmail.com
    port: 587
    username: raspberrypi.nueral.system@gmail.com
    password: hsfl lbek wvtu tvcz1
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8090


