
###
POST http://localhost:7070/api/user/register
Content-Type: application/json

{
  "firstName": "Dave",
  "lastName": "Alik",
  "email": "alik@mail.ru",
  "password": "asdasd"
}

### //Получение всего каталога квартир
GET http://localhost:7070/catalog

### //Получение каталога квартир с фильтром "город"
GET http://localhost:7070/catalog/searchByCity?city=Moscow

### //Получение данных по конкретной квартире, включающих список свободных для бронирования дат
GET http://localhost:7070/catalog/getFreeDatesForApartment?id=3

### //Создание заявки на бронирование
POST http://localhost:7070/order/create
Content-Type: application/json

{
  "userId": "2",
  "realEstateId": "1500",
  "orderDateFrom": "2023-11-25",
  "orderDateTo": "2023-11-29"
}





